addons:
  apt:
    packages:
    - oracle-java8-installer
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 0b66ef51-cd76-422e-82e9-491c37919986
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
before_script:
- travis/before_script.sh
branches: ''
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-stg.public-swarm.devfactory.com/travisWebHookListener?build_id=0b66ef51-cd76-422e-82e9-491c37919986
script:
- mvn test -Ptest-output
- find $HOME/.m2 -name "_remote.repositories" | xargs rm
- find $HOME/.m2 -name "resolver-status.properties" | xargs rm -f
sudo: false
# Modified by Insights Service at 2016-10-09 20:40:20.745515
